<a href="https://colab.research.google.com/github/CPTR295/NLP-Basic-Using-Pytorch/blob/main/Continuous_Bag_of_Words.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import urllib.request

In [2]:
#Dataset
url = "https://www.gutenberg.org/cache/epub/84/pg84.txt"
output_file = "/content/frankenstein.txt"
urllib.request.urlretrieve(url, output_file)

print("Downloaded to:", output_file)

Downloaded to: /content/frankenstein.txt

In [3]:
print(os.path.getsize("/content/frankenstein.txt"))

448885

In [4]:
import os
from argparse import Namespace
import collections
import nltk.data #Natural Language Toolkit (NLTK) library used to find, load, and manage external datasets, pre-trained models, and corpora in Python
import numpy as np
import pandas as pd
import re
from tqdm import tqdm_notebook

In [5]:
args = Namespace(
    raw_dataset_txt="/content/frankenstein.txt",
    train_proportion=0.7,
    val_proportion=0.15,
    test_proportion=0.15,
    window_size = 5,
    output_munged_csv="/content/frankenstein_with_splits.csv",
    seed=1337
)

In [6]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')
with open(args.raw_dataset_txt) as fp:
  book = fp.read()
sentences = tokenizer.tokenize(book)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [7]:
print(len(sentences))
print(sentences[:30])

3199
['The Project Gutenberg eBook of Frankenstein; or, the modern prometheus\n    \nThis eBook is for the use of anyone anywhere in the United States and\nmost other parts of the world at no cost and with almost no restrictions\nwhatsoever.', 'You may copy it, give it away or re-use it under the terms\nof the Project Gutenberg License included with this eBook or online\nat www.gutenberg.org.', 'If you are not located in the United States,\nyou will have to check the laws of the country where you are located\nbefore using this eBook.', 'Title: Frankenstein; or, the modern prometheus\n\nAuthor: Mary Wollstonecraft Shelley\n\n\n        \nRelease date: October 1, 1993 [eBook #84]\n                Most recently updated: February 10, 2026\n\nLanguage: English\n\nOther information and formats: www.gutenberg.org/ebooks/84\n\nCredits: Judith Boss, Christy Phillips, Lynn Hanninen and David Meltzer.', 'HTML version by Al Haines.', 'Further corrections by Menno de Leeuw.', '*** START OF THE PROJECT GUTENBERG EBOOK FRANKENSTEIN; OR, THE MODERN PROMETHEUS ***\n\nFrankenstein;\n\nor, the Modern Prometheus\n\nby Mary Wollstonecraft (Godwin) Shelley\n\n\n CONTENTS\n\n Letter 1\n Letter 2\n Letter 3\n Letter 4\n Chapter 1\n Chapter 2\n Chapter 3\n Chapter 4\n Chapter 5\n Chapter 6\n Chapter 7\n Chapter 8\n Chapter 9\n Chapter 10\n Chapter 11\n Chapter 12\n Chapter 13\n Chapter 14\n Chapter 15\n Chapter 16\n Chapter 17\n Chapter 18\n Chapter 19\n Chapter 20\n Chapter 21\n Chapter 22\n Chapter 23\n Chapter 24\n\n\n\n\nLetter 1\n\n_To Mrs. Saville, England._\n\n\nSt. Petersburgh, Dec. 11th, 17—.', 'You will rejoice to hear that no disaster has accompanied the\ncommencement of an enterprise which you have regarded with such evil\nforebodings.', 'I arrived here yesterday, and my first task is to assure\nmy dear sister of my welfare and increasing confidence in the success\nof my undertaking.', 'I am already far north of London, and as I walk in the streets of\nPetersburgh, I feel a cold northern breeze play upon my cheeks, which\nbraces my nerves and fills me with delight.', 'Do you understand this\nfeeling?', 'This breeze, which has travelled from the regions towards\nwhich I am advancing, gives me a foretaste of those icy climes.', 'Inspirited by this wind of promise, my daydreams become more fervent\nand vivid.', 'I try in vain to be persuaded that the pole is the seat of\nfrost and desolation; it ever presents itself to my imagination as the\nregion of beauty and delight.', 'There, Margaret, the sun is for ever\nvisible, its broad disk just skirting the horizon and diffusing a\nperpetual splendour.', 'There—for with your leave, my sister, I will put\nsome trust in preceding navigators—there snow and frost are banished;\nand, sailing over a calm sea, we may be wafted to a land surpassing in\nwonders and in beauty every region hitherto discovered on the habitable\nglobe.', 'Its productions and features may be without example, as the\nphenomena of the heavenly bodies undoubtedly are in those undiscovered\nsolitudes.', 'What may not be expected in a country of eternal light?', 'I\nmay there discover the wondrous power which attracts the needle and may\nregulate a thousand celestial observations that require only this\nvoyage to render their seeming eccentricities consistent for ever.', 'I\nshall satiate my ardent curiosity with the sight of a part of the world\nnever before visited, and may tread a land never before imprinted by\nthe foot of man.', 'These are my enticements, and they are sufficient to\nconquer all fear of danger or death and to induce me to commence this\nlaborious voyage with the joy a child feels when he embarks in a little\nboat, with his holiday mates, on an expedition of discovery up his\nnative river.', 'But supposing all these conjectures to be false, you\ncannot contest the inestimable benefit which I shall confer on all\nmankind, to the last generation, by discovering a passage near the pole\nto those countries, to reach which at present so many months are\nrequisite; or by ascertaining the secret of the magnet, which, if at\nall possible, can only be effected by an undertaking such as mine.', 'These reflections have dispelled the agitation with which I began my\nletter, and I feel my heart glow with an enthusiasm which elevates me\nto heaven, for nothing contributes so much to tranquillise the mind as\na steady purpose—a point on which the soul may fix its intellectual\neye.', 'This expedition has been the favourite dream of my early years.', 'I\nhave read with ardour the accounts of the various voyages which have\nbeen made in the prospect of arriving at the North Pacific Ocean\nthrough the seas which surround the pole.', 'You may remember that a\nhistory of all the voyages made for purposes of discovery composed the\nwhole of our good Uncle Thomas’ library.', 'My education was neglected,\nyet I was passionately fond of reading.', 'These volumes were my study\nday and night, and my familiarity with them increased that regret which\nI had felt, as a child, on learning that my father’s dying injunction\nhad forbidden my uncle to allow me to embark in a seafaring life.', 'These visions faded when I perused, for the first time, those poets\nwhose effusions entranced my soul and lifted it to heaven.', 'I also\nbecame a poet and for one year lived in a paradise of my own creation;\nI imagined that I also might obtain a niche in the temple where the\nnames of Homer and Shakespeare are consecrated.']

In [8]:
#Clean Sentences
def preprocess_text(text):
  text = ' '.join(word.lower() for word in text.split(" "))
  text = re.sub(r"([.,!?])", r" \1 ", text)
  text = re.sub(r"[^a-zA-Z.,!?]+", r" ", text)
  return text

In [9]:
cleaned_sentences = [preprocess_text(sentence) for sentence in sentences]

In [10]:
MASK_TOKEN = '<MASK>'

In [11]:
#Create Windows
flatten = lambda outer_list: [item for inner_list in outer_list for item in inner_list] #Sqeeze all arrays to 1D
#Slidding window with <MASK>'s as padding
windows = flatten([list(nltk.ngrams([MASK_TOKEN]*args.window_size + sentence.split(' ') + [MASK_TOKEN]* \
                                    args.window_size,args.window_size*2+1)) for sentence in tqdm_notebook(cleaned_sentences)])

/tmp/ipykernel_374/759950361.py:5: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  args.window_size,args.window_size*2+1)) for sentence in tqdm_notebook(cleaned_sentences)])

  0%|          | 0/3199 [00:00<?, ?it/s]

In [12]:
#Create CBOW Data
data =[]
for window in tqdm_notebook(windows):
  target_token = window[args.window_size]
  context =[]
  for i,token in enumerate (window):
    if token==MASK_TOKEN or i==args.window_size:
      continue
    else:
      context.append(token)
  data.append([' '.join(token for token in context),target_token])

/tmp/ipykernel_374/2067953158.py:3: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for window in tqdm_notebook(windows):

  0%|          | 0/90578 [00:00<?, ?it/s]

In [13]:
cbow_data = pd.DataFrame(data,columns=["context","target"])

In [14]:
cbow_data.head()

                                             context     target
0            project gutenberg ebook of frankenstein        the
1             the gutenberg ebook of frankenstein or    project
2             the project ebook of frankenstein or ,  gutenberg
3     the project gutenberg of frankenstein or , the      ebook
4  the project gutenberg ebook frankenstein or , ...         of

In [15]:
#Split the data
n=len(cbow_data)
def get_split(row_num):
  if row_num <= n*args.train_proportion:
    return 'train'
  elif (row_num > n*args.train_proportion) and (row_num <= n*args.train_proportion + n*args.val_proportion):
    return 'val'
  else:
    return 'test'

cbow_data['split'] = cbow_data.apply(lambda row: get_split(row.name),axis=1)

In [16]:
cbow_data.head()

                                             context     target  split
0            project gutenberg ebook of frankenstein        the  train
1             the gutenberg ebook of frankenstein or    project  train
2             the project ebook of frankenstein or ,  gutenberg  train
3     the project gutenberg of frankenstein or , the      ebook  train
4  the project gutenberg ebook frankenstein or , ...         of  train

In [17]:
cbow_data.split.value_counts()

split
train    63405
val      13587
test     13586
Name: count, dtype: int64

In [18]:
cbow_data.to_csv(args.output_munged_csv, index=False)

Learning Embeddings with Continuous Bag of Words (CBOW)

In [19]:
import os
from argparse import Namespace
from collections import Counter
import json
import re
import string

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm_notebook

In [82]:
class Vocabulary(object):
  def __init__(self,token_to_idx=None,mask_token='<MASK>',add_unk=True,unk_token='<UNK>'):
    if token_to_idx is None:
      token_to_idx = {}
    self._token_to_idx = token_to_idx
    self._idx_to_token = {idx:token for token,idx in self._token_to_idx.items()}
    self._add_unk = add_unk
    self._unk_token = unk_token
    self._mask_token = mask_token
    self.mask_index = self.add_token(self._mask_token)
    if add_unk:
      self.unk_index = self.add_token(unk_token)

  def to_serializable(self):
    return {'token_to_idx':self._token_to_idx,
            'add_unk':self._add_unk,
            'unk_token':self._unk_token,
            'mask_token':self._mask_token}

  @classmethod
  def from_serializable(cls,contents):
    return cls(**contents)

  def add_token(self,token):
    if token in self._token_to_idx:
      index = self._token_to_idx[token]
    else:
      index = len(self._token_to_idx)
      self._token_to_idx[token] = index
      self._idx_to_token[index] = token
    return index

  def add_many(self,tokens):
    return [self.add_token(token) for token in tokens]

  def lookup_token(self,token):
    if self.unk_index>=0:
      return self._token_to_idx.get(token,self.unk_index)
    else:
      return self._token_to_idx[token]

  def lookup_index(self,index):
    if index not in self._idx_to_token:
      raise KeyError('The index not in vocab')
    return self._idx_to_token[index]

  def __str__(self):
    return f'<Vocabulary(size={len(self)})>'

  def __len__(self):
    return len(self._token_to_idx)

  def __str__(self) -> str:
    return f'<Vocabulary(size={len(self)})>'

  def __len__(self) -> int:
    return len(self._token_to_idx)

In [90]:
class CWOBVectorizer(object):
  def __init__(self,cbow_vocab):
    self.cbow_vocab = cbow_vocab

  def vectorize(self,context,vector_lenght=-1):
    indices = [self.cbow_vocab.lookup_token(token) for token in context.split(' ')]
    if vector_lenght < 0:
      vector_lenght = len(indices)
    out_vector = np.zeros(vector_lenght,dtype=np.int64)
    out_vector[:len(indices)] = indices
    out_vector[len(indices):]=self.cbow_vocab.mask_index
    return out_vector

  @classmethod
  def from_dataframe(cls,cbow_df):
    cbow_vocab = Vocabulary()
    for index,row in cbow_df.iterrows():
      for token in row.context.split(' '):
        cbow_vocab.add_token(token)
      cbow_vocab.add_token(row.target)
    return cls(cbow_vocab)

  @classmethod
  def from_serializable(cls,contents):
    cbow_vocab = Vocabulary.from_serializable(contents['cbow_vocab'])
    return cls(cbow_vocab=cbow_vocab)

  def to_serializable(self):
    return {'cbow_vocab':self.cbow_vocab.to_serializable()}

In [84]:
class CBOWDataset(Dataset):
  def __init__(self,cbow_df,vectorizer):
    self.cbow_df = cbow_df
    self._vectorizer = vectorizer

    measure_len = lambda context:len(context.split(' '))
    self._max_seq_length = max(map(measure_len,cbow_df.context))

    self.train_df = self.cbow_df[self.cbow_df.split=='train']
    self.train_size = len(self.train_df)

    self.val_df = self.cbow_df[self.cbow_df.split=='val']
    self.validation_size = len(self.val_df)

    self.test_df = self.cbow_df[self.cbow_df.split=='test']
    self.test_size = len(self.test_df)

    self._lookup_dict = {'train':(self.train_df,self.train_size),
                         'val':(self.val_df,self.validation_size),
                         'test':(self.test_df,self.test_size)}
    self.set_split('train')

  @classmethod
  def load_dataset_make_vectorizer(cls,cbow_csv):
    cbow_df = pd.read_csv(cbow_csv)
    train_cbow_df = cbow_df[cbow_df.split=='train']
    return cls(cbow_df,CWOBVectorizer.from_dataframe(train_cbow_df))

  @classmethod
  def load_dataset_and_load_vectorizer(cls,cbow_csv,vectorizer_filepath):
    cbow_df = pd.read_csv(cbow_csv)
    vectorizer = cls.load_vectorizer_only(vectorizer_filepath)
    return cls(cbow_df,vectorizer)

  @staticmethod
  def load_vectorizer_only(vectorizer_filepath):
    with open(vectorizer_filepath) as fp:
      return CWOBVectorizer.from_serializable(json.load(fp))

  def save_vectorizer(self,vectorizer_filepath):
    with open(vectorizer_filepath,'w') as fp:
      json.dump(self._vectorizer.to_serializable(),fp)

  def get_vectorizer(self):
    return self._vectorizer

  def set_split(self,split='train'):
    self._target_split = split
    self._target_df,self._target_size = self._lookup_dict[split]

  def __len__(self):
    return self._target_size

  def __getitem__(self, index):
    row = self._target_df.iloc[index]
    context_vector = self._vectorizer.vectorize(row.context,self._max_seq_length)
    target_index = self._vectorizer.cbow_vocab.lookup_token(row.target)
    return {'x_data':context_vector,'y_target':target_index}

  def get_num_batches(self,batch_size):
    return len(self)//batch_size

In [61]:
def generate_batches(dataset,batch_size,shuffle=True,drop_last=True,device='cpu'):
  dataloader = DataLoader(dataset=dataset,batch_size=batch_size,shuffle=shuffle,drop_last=drop_last)
  for data_dict in dataloader:
    out_data_dict = {}
    for name,tensor in data_dict.items():
      out_data_dict[name]=data_dict[name].to(device)
    yield out_data_dict

In [62]:
class CBOWClassifer(nn.Module):
  def __init__(self,vocabulary_size,embedding_size,padding_idx):
    super(CBOWClassifer,self).__init__()
    self.embedding = nn.Embedding(num_embeddings=vocabulary_size,embedding_dim=embedding_size,padding_idx=padding_idx)
    self.fc1 = nn.Linear(in_features = embedding_size,out_features=vocabulary_size)

  def forward(self,x_in,apply_softmax=False):
    x_embedded_sum = F.dropout(self.embedding(x_in).sum(dim=1),0.3)
    y_out = self.fc1(x_embedded_sum)
    if apply_softmax:
      y_out = F.softmax(y_out,dim=1)
    return y_out

In [63]:
def make_train_state(args):
    return {'stop_early': False,
            'early_stopping_step': 0,
            'early_stopping_best_val': 1e8,
            'learning_rate': args.learning_rate,
            'epoch_index': 0,
            'train_loss': [],
            'train_acc': [],
            'val_loss': [],
            'val_acc': [],
            'test_loss': -1,
            'test_acc': -1,
            'model_filename': args.model_state_file}

In [64]:
def update_train_state(args, model, train_state):
   # Save one model at least
    if train_state['epoch_index'] == 0:
        torch.save(model.state_dict(), train_state['model_filename'])
        train_state['stop_early'] = False

    # Save model if performance improved
    elif train_state['epoch_index'] >= 1:
        loss_tm1, loss_t = train_state['val_loss'][-2:]

        # If loss worsened
        if loss_t >= train_state['early_stopping_best_val']:
            # Update step
            train_state['early_stopping_step'] += 1
        # Loss decreased
        else:
            # Save the best model
            if loss_t < train_state['early_stopping_best_val']:
                torch.save(model.state_dict(), train_state['model_filename'])

            # Reset early stopping step
            train_state['early_stopping_step'] = 0

        # Stop early ?
        train_state['stop_early'] = \
            train_state['early_stopping_step'] >= args.early_stopping_criteria

    return train_state

In [65]:
def compute_accuracy(y_pred, y_target):
    _, y_pred_indices = y_pred.max(dim=1)
    n_correct = torch.eq(y_pred_indices, y_target).sum().item()
    return n_correct / len(y_pred_indices) * 100

In [66]:
def set_seed_everywhere(seed, cuda):
    np.random.seed(seed)
    torch.manual_seed(seed)
    if cuda:
        torch.cuda.manual_seed_all(seed)

def handle_dirs(dirpath):
    if not os.path.exists(dirpath):
        os.makedirs(dirpath)

In [67]:
args = Namespace(
    # Data and Path information
    cbow_csv="/content/frankenstein_with_splits.csv",
    vectorizer_file="vectorizer.json",
    model_state_file="model.pth",
    save_dir="/content/",
    # Model hyper parameters
    embedding_size=50,
    # Training hyper parameters
    seed=1337,
    num_epochs=100,
    learning_rate=0.0001,
    batch_size=32,
    early_stopping_criteria=5,
    # Runtime options
    cuda=True,
    catch_keyboard_interrupt=True,
    reload_from_files=False,
    expand_filepaths_to_save_dir=True
)

In [68]:
if args.expand_filepaths_to_save_dir:
    args.vectorizer_file = os.path.join(args.save_dir,
                                        args.vectorizer_file)

    args.model_state_file = os.path.join(args.save_dir,
                                         args.model_state_file)

    print("Expanded filepaths: ")
    print("\t{}".format(args.vectorizer_file))
    print("\t{}".format(args.model_state_file))

Expanded filepaths:
	/content/vectorizer.json
	/content/model.pth

In [69]:
# Check CUDA
if not torch.cuda.is_available():
    args.cuda = False

args.device = torch.device("cuda" if args.cuda else "cpu")
print("Using CUDA: {}".format(args.cuda))

Using CUDA: True

In [70]:
set_seed_everywhere(args.seed, args.cuda)
handle_dirs(args.save_dir)

In [91]:
if args.reload_from_files:
    print("Loading dataset and loading vectorizer")
    dataset = CBOWDataset.load_dataset_and_load_vectorizer(args.cbow_csv,
                                                           args.vectorizer_file)
else:
    print("Loading dataset and creating vectorizer")
    dataset = CBOWDataset.load_dataset_make_vectorizer(args.cbow_csv)
    dataset.save_vectorizer(args.vectorizer_file)

Loading dataset and creating vectorizer

In [92]:
vectorizer = dataset.get_vectorizer()
classifier = CBOWClassifer(vocabulary_size=len(vectorizer.cbow_vocab),
                            embedding_size=args.embedding_size,
                            padding_idx=0)

In [93]:
classifier = classifier.to(args.device)
loss_func = nn.CrossEntropyLoss()
optimizer = optim.Adam(classifier.parameters(),lr=args.learning_rate)
scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer=optimizer,mode='min',factor=0.5,patience=1)

In [94]:
train_state = make_train_state(args)

In [96]:
try:
  for epoch_index in range(args.num_epochs):
    dataset.set_split('train')
    classifier.train()
    batch_generator = generate_batches(dataset,batch_size=args.batch_size,device=args.device)
    loss=0.0
    acc=0.0
    for batch_index,batch_dict in enumerate(batch_generator):
      optimizer.zero_grad()
      y_pred = classifier(x_in=batch_dict['x_data'])
      loss = loss_func(y_pred,batch_dict['y_target'])
      loss_batch = loss.item()
      loss.backward()
      optimizer.step()
      acc_batch = compute_accuracy(y_pred,batch_dict['y_target'])
      loss+=(loss_batch-loss)/(batch_index+1)
      acc+=(acc_batch-acc)/(batch_index+1)
    train_state['train_loss'].append(loss)
    train_state['train_acc'].append(acc)

    dataset.set_split('val')
    batch_generator = generate_batches(dataset,batch_size=args.batch_size,device=args.device)
    loss=0.0
    acc=0.0
    classifier.eval()
    with torch.no_grad():
      for batch_index,batch_dict in enumerate(batch_generator):
        y_pred = classifier(x_in=batch_dict['x_data'])
        loss = loss_func(y_pred,batch_dict['y_target'])
        loss_batch = loss.item()
        acc_batch = compute_accuracy(y_pred,batch_dict['y_target'])
        loss+=(loss_batch-loss)/(batch_index+1)
        acc+=(acc_batch-acc)/(batch_index+1)
      train_state['val_acc'].append(acc)
      train_state['val_loss'].append(loss)

    train_state = update_train_state(args=args,model=classifier,train_state=train_state)
    scheduler.step(train_state['val_loss'][-1])
    if train_state['stop_early']:
      break
    print("Epoch: {}/{}...".format(epoch_index+1,args.num_epochs),
          "Train Loss: {:.3f}".format(train_state['train_loss'][-1]),
          "Train Acc: {:.2f}".format(train_state['train_acc'][-1]),
          "Val Loss: {:.3f}".format(train_state['val_loss'][-1]),
          "Val Acc: {:.2f}".format(train_state['val_acc'][-1]))


except KeyboardInterrupt:
  print('Exiting')

Epoch: 1/100... Train Loss: 8.270 Train Acc: 5.21 Val Loss: 6.950 Val Acc: 6.14
Epoch: 2/100... Train Loss: 7.711 Train Acc: 7.25 Val Loss: 7.681 Val Acc: 7.86
Epoch: 3/100... Train Loss: 7.466 Train Acc: 8.55 Val Loss: 7.292 Val Acc: 9.20
Epoch: 4/100... Train Loss: 5.230 Train Acc: 9.25 Val Loss: 7.224 Val Acc: 9.07
Epoch: 5/100... Train Loss: 7.606 Train Acc: 9.70 Val Loss: 6.649 Val Acc: 9.68
Epoch: 6/100... Train Loss: 6.643 Train Acc: 10.12 Val Loss: 7.860 Val Acc: 10.03
Epoch: 7/100... Train Loss: 5.736 Train Acc: 10.45 Val Loss: 7.633 Val Acc: 10.28
Epoch: 8/100... Train Loss: 6.411 Train Acc: 10.84 Val Loss: 7.017 Val Acc: 10.61
Epoch: 9/100... Train Loss: 5.804 Train Acc: 10.88 Val Loss: 6.985 Val Acc: 10.58
Epoch: 10/100... Train Loss: 5.926 Train Acc: 10.98 Val Loss: 6.380 Val Acc: 10.39
Epoch: 11/100... Train Loss: 6.293 Train Acc: 10.94 Val Loss: 8.383 Val Acc: 10.69
Epoch: 12/100... Train Loss: 6.025 Train Acc: 11.06 Val Loss: 6.813 Val Acc: 10.76
Epoch: 13/100... Train Loss: 5.173 Train Acc: 11.11 Val Loss: 7.961 Val Acc: 10.58
Epoch: 14/100... Train Loss: 6.457 Train Acc: 11.21 Val Loss: 7.091 Val Acc: 10.54
Epoch: 15/100... Train Loss: 6.270 Train Acc: 11.23 Val Loss: 6.881 Val Acc: 10.84
Epoch: 16/100... Train Loss: 6.743 Train Acc: 11.18 Val Loss: 8.419 Val Acc: 10.86
Epoch: 17/100... Train Loss: 5.712 Train Acc: 11.38 Val Loss: 7.794 Val Acc: 10.92
Epoch: 18/100... Train Loss: 6.229 Train Acc: 11.20 Val Loss: 7.342 Val Acc: 10.98
Epoch: 19/100... Train Loss: 6.056 Train Acc: 11.23 Val Loss: 7.147 Val Acc: 10.58
Epoch: 20/100... Train Loss: 6.911 Train Acc: 11.27 Val Loss: 7.642 Val Acc: 10.70
Epoch: 21/100... Train Loss: 5.918 Train Acc: 11.25 Val Loss: 6.197 Val Acc: 10.77
Epoch: 22/100... Train Loss: 5.868 Train Acc: 11.18 Val Loss: 6.131 Val Acc: 10.81
Epoch: 23/100... Train Loss: 6.399 Train Acc: 11.36 Val Loss: 7.929 Val Acc: 10.94
Epoch: 24/100... Train Loss: 5.423 Train Acc: 11.23 Val Loss: 7.864 Val Acc: 10.87
Epoch: 25/100... Train Loss: 5.893 Train Acc: 11.26 Val Loss: 6.912 Val Acc: 10.89
Epoch: 26/100... Train Loss: 5.821 Train Acc: 11.16 Val Loss: 7.135 Val Acc: 10.71
Epoch: 27/100... Train Loss: 6.340 Train Acc: 11.17 Val Loss: 7.307 Val Acc: 10.74
Epoch: 28/100... Train Loss: 6.134 Train Acc: 11.17 Val Loss: 7.972 Val Acc: 10.77
Epoch: 29/100... Train Loss: 6.257 Train Acc: 11.25 Val Loss: 7.016 Val Acc: 11.09
Epoch: 30/100... Train Loss: 6.617 Train Acc: 11.33 Val Loss: 7.961 Val Acc: 11.07
Epoch: 31/100... Train Loss: 6.723 Train Acc: 11.23 Val Loss: 7.606 Val Acc: 10.94
Epoch: 32/100... Train Loss: 6.432 Train Acc: 11.24 Val Loss: 5.989 Val Acc: 10.97
Epoch: 33/100... Train Loss: 6.321 Train Acc: 11.30 Val Loss: 7.092 Val Acc: 10.66
Epoch: 34/100... Train Loss: 5.546 Train Acc: 11.25 Val Loss: 6.706 Val Acc: 10.86
Epoch: 35/100... Train Loss: 5.804 Train Acc: 11.17 Val Loss: 7.510 Val Acc: 10.88
Epoch: 36/100... Train Loss: 6.598 Train Acc: 11.28 Val Loss: 8.175 Val Acc: 10.87
Epoch: 37/100... Train Loss: 6.096 Train Acc: 11.30 Val Loss: 8.204 Val Acc: 10.88
Epoch: 38/100... Train Loss: 6.564 Train Acc: 11.26 Val Loss: 7.001 Val Acc: 10.89
Epoch: 39/100... Train Loss: 6.169 Train Acc: 11.28 Val Loss: 6.266 Val Acc: 10.54
Epoch: 40/100... Train Loss: 5.494 Train Acc: 11.38 Val Loss: 6.390 Val Acc: 10.56
Epoch: 41/100... Train Loss: 6.097 Train Acc: 11.17 Val Loss: 7.994 Val Acc: 10.69
Epoch: 42/100... Train Loss: 7.271 Train Acc: 11.17 Val Loss: 6.032 Val Acc: 10.63
Epoch: 43/100... Train Loss: 6.072 Train Acc: 11.13 Val Loss: 6.720 Val Acc: 10.87
Epoch: 44/100... Train Loss: 6.137 Train Acc: 11.23 Val Loss: 7.632 Val Acc: 10.67
Epoch: 45/100... Train Loss: 6.149 Train Acc: 11.31 Val Loss: 6.257 Val Acc: 10.96
Epoch: 46/100... Train Loss: 7.019 Train Acc: 11.21 Val Loss: 7.260 Val Acc: 10.96
Epoch: 47/100... Train Loss: 5.800 Train Acc: 11.26 Val Loss: 7.210 Val Acc: 10.72
Epoch: 48/100... Train Loss: 6.538 Train Acc: 11.35 Val Loss: 8.756 Val Acc: 10.72
Epoch: 49/100... Train Loss: 6.109 Train Acc: 11.19 Val Loss: 6.118 Val Acc: 10.96
Exiting

In [101]:
dataset.set_split('test')
batch_generator = generate_batches(dataset,
                                   batch_size=args.batch_size,
                                   device=args.device)
running_loss = 0.0
running_acc = 0.0
classifier.eval()
with torch.no_grad():
    for batch_index,batch_dict in enumerate(batch_generator):
      y_pred = classifier(x_in=batch_dict['x_data'])
      loss = loss_func(y_pred,batch_dict['y_target'])
      loss_batch = loss.item()
      acc_batch = compute_accuracy(y_pred,batch_dict['y_target'])
      loss+=(loss_batch-loss)/(batch_index+1)
      acc+=(acc_batch-acc)/(batch_index+1)
train_state['test_loss'] = loss
train_state['test_acc'] = acc
print("Test loss: {};".format(train_state['test_loss']))
print("Test Accuracy: {}".format(train_state['test_acc']))

Test loss: 8.674707412719727;
Test Accuracy: 10.88590801886792

Trained Embeddings

In [97]:
def pretty_print(results):
  for item in results:
        print ("...[%.2f] - %s"%(item[1], item[0]))

def get_closest(target_word, word_to_idx, embeddings, n=5):
  word_embedding = embeddings[word_to_idx[target_word.lower()]]
  distances = []
  for word, index in word_to_idx.items():
      if word == "<MASK>" or word == target_word:
          continue
      distances.append((word, torch.dist(word_embedding, embeddings[index])))

  results = sorted(distances, key=lambda x: x[1])[1:n+2]
  return results

In [98]:
word = input('Enter a word: ')
embeddings = classifier.embedding.weight.data
word_to_idx = vectorizer.cbow_vocab._token_to_idx
pretty_print(get_closest(word, word_to_idx, embeddings, n=5))

Enter a word: monster
...[6.59] - recess
...[6.72] - obliged
...[6.93] - ensure
...[6.93] - continuing
...[6.94] - william
...[6.94] - afforded